// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\EdgeDetectionAndOverlayHDL\Edge_Detection.v
// Created: 2023-11-17 13:10:32
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Edge_Detection
// Source Path: EdgeDetectionAndOverlayHDL/Pixel-Stream HDL Model/Edge Detection
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Edge_Detection
          (clk,
           reset,
           enb,
           ctrlIn_hStart,
           ctrlIn_hEnd,
           ctrlIn_vStart,
           ctrlIn_vEnd,
           ctrlIn_valid,
           ctrlOut_hStart,
           ctrlOut_hEnd,
           ctrlOut_vStart,
           ctrlOut_vEnd,
           ctrlOut_valid);


  input   clk;
  input   reset;
  input   enb;
  input   ctrlIn_hStart;
  input   ctrlIn_hEnd;
  input   ctrlIn_vStart;
  input   ctrlIn_vEnd;
  input   ctrlIn_valid;
  output  ctrlOut_hStart;
  output  ctrlOut_hEnd;
  output  ctrlOut_vStart;
  output  ctrlOut_vEnd;
  output  ctrlOut_valid;


  wire Edge_Detector_out2_hStart;
  wire Edge_Detector_out2_hEnd;
  wire Edge_Detector_out2_vStart;
  wire Edge_Detector_out2_vEnd;
  wire Edge_Detector_out2_valid;


  Edge_Detector u_Edge_Detector (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .in1_hStart(ctrlIn_hStart),
                                 .in1_hEnd(ctrlIn_hEnd),
                                 .in1_vStart(ctrlIn_vStart),
                                 .in1_vEnd(ctrlIn_vEnd),
                                 .in1_valid(ctrlIn_valid),
                                 .out1_hStart(Edge_Detector_out2_hStart),
                                 .out1_hEnd(Edge_Detector_out2_hEnd),
                                 .out1_vStart(Edge_Detector_out2_vStart),
                                 .out1_vEnd(Edge_Detector_out2_vEnd),
                                 .out1_valid(Edge_Detector_out2_valid)
                                 );
  assign ctrlOut_hStart = Edge_Detector_out2_hStart;

  assign ctrlOut_hEnd = Edge_Detector_out2_hEnd;

  assign ctrlOut_vStart = Edge_Detector_out2_vStart;

  assign ctrlOut_vEnd = Edge_Detector_out2_vEnd;

  assign ctrlOut_valid = Edge_Detector_out2_valid;

endmodule  // Edge_Detection

