// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\EdgeDetectionAndOverlayHDL\GateProcessData.v
// Created: 2023-11-17 13:10:32
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: GateProcessData
// Source Path: EdgeDetectionAndOverlayHDL/Pixel-Stream HDL Model/Edge Detection/Edge Detector/LineBuffer/GateProcessData
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module GateProcessData
          (clk,
           reset,
           enb,
           processDataIn,
           validIn,
           dumping,
           outputData,
           processData);


  input   clk;
  input   reset;
  input   enb;
  input   processDataIn;
  input   validIn;
  input   dumping;
  input   outputData;
  output  processData;


  wire processNull;
  reg  validREG;
  wire validOrDumping;
  wire processValid;


  assign processNull = 1'b0;



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        validREG <= 1'b0;
      end
      else begin
        if (enb) begin
          validREG <= validIn;
        end
      end
    end



  assign validOrDumping = validREG | dumping;



  assign processValid = processDataIn & validOrDumping;



  assign processData = (outputData == 1'b0 ? processNull :
              processValid);



endmodule  // GateProcessData

